In [1]:
import pandas as pd
df = pd.read_csv("../data/data_moods.csv")
df.head()

,name,album,artist,id,release_date,popularity,length,danceability,acousticness,energy,instrumentalness,liveness,valence,loudness,speechiness,tempo,key,time_signature,mood
0,1999,1999,Prince,2H7PHVdQ3mXqEHXcvclTB0,1982-10-27,68,379266,0.866,0.13700,0.730,0.000000,0.0843,0.625,-8.201,0.0767,118.523,5,4,Happy
1,23,23,Blonde Redhead,4HIwL9ii9CcXpTOTzMq0MP,2007-04-16,43,318800,0.381,0.01890,0.832,0.196000,0.1530,0.166,-5.069,0.0492,120.255,8,4,Sad
2,9 Crimes,9,Damien Rice,5GZEeowhvSieFDiR8fQ2im,2006-11-06,60,217946,0.346,0.91300,0.139,0.000077,0.0934,0.116,-15.326,0.0321,136.168,0,4,Sad
3,99 Luftballons,99 Luftballons,Nena,6HA97v4wEGQ5TUClRM0XLc,1984-08-21,2,233000,0.466,0.08900,0.438,0.000006,0.1130,0.587,-12.858,0.0608,193.100,4,4,Happy
4,A Boy Brushed Red Living In Black And White,They're Only Chasing Safety,Underoath,47IWLfIKOKhFnz1FUEUIkE,2004-01-01,60,268000,0.419,0.00171,0.932,0.000000,0.1370,0.445,-3.604,0.1060,169.881,1,4,Energetic

In [2]:
df.shape #686 rows, 19 cols

(686, 19)

In [17]:
df.info() 
#found no missing values within dataset and identified data types

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 686 entries, 0 to 685
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              686 non-null    object
 1   album             686 non-null    object
 2   artist            686 non-null    object
 3   id                686 non-null    object
 4   release_date      686 non-null    datetime64[ns]
 5   popularity        686 non-null    int64
 6   length            686 non-null    int64
 7   danceability      686 non-null    float64
 8   acousticness      686 non-null    float64
 9   energy            686 non-null    float64
 10  instrumentalness  686 non-null    float64
 11  liveness          686 non-null    float64
 12  valence           686 non-null    float64
 13  loudness          686 non-null    float64
 14  speechiness       686 non-null    float64
 15  tempo             686 non-null    float64
 16  key               686 non-null    int64
 17  time_signature    686 non-null    int64
 18  mood              686 non-null    object
dtypes: datetime64[ns](1), float64(9), int64(4), object(5)
memory usage: 102.0+ KB

In [13]:
df.describe()

,release_date,popularity,length,danceability,acousticness,energy,instrumentalness,liveness,valence,loudness,speechiness,tempo,key,time_signature
count,686,686.000000,686.000000,686.000000,686.000000,686.000000,686.000000,686.000000,686.000000,686.000000,686.000000,686.000000,686.000000,686.000000
mean,2012-04-29 14:37:26.064140032,41.534985,221791.485423,0.500553,0.449749,0.507693,0.349610,0.166867,0.342438,-11.531020,0.053946,119.134679,5.335277,3.870262
min,1963-03-22 00:00:00,0.000000,76773.000000,0.078900,0.000005,0.001290,0.000000,0.031800,0.035300,-42.018000,0.023200,50.960000,0.000000,1.000000
25%,2007-01-16 00:00:00,30.000000,179114.500000,0.388000,0.014825,0.202000,0.000034,0.092500,0.131250,-15.858750,0.033200,99.008750,2.000000,4.000000
50%,2018-07-13 00:00:00,47.000000,213273.000000,0.505000,0.359000,0.495500,0.026350,0.111000,0.282000,-9.358000,0.040700,120.071000,6.000000,4.000000
75%,2019-11-18 18:00:00,57.000000,254569.750000,0.612000,0.905750,0.844000,0.858250,0.173750,0.508750,-5.634500,0.057375,132.953250,9.000000,4.000000
max,2020-08-07 00:00:00,88.000000,518373.000000,0.941000,0.996000,0.994000,0.966000,0.963000,0.977000,1.342000,0.416000,217.950000,11.000000,5.000000
std,NaN,23.045707,63399.058492,0.158955,0.410729,0.326490,0.410517,0.142128,0.252304,7.468629,0.041374,28.978685,3.550858,0.500297

In [15]:
df.duplicated().sum() #no duplicates, so no need to remove

np.int64(0)

In [16]:
#checking if id column is unique for all rows so that I can keep as primary key of table
df['id'].nunique()

686

In [7]:
df['release_date'] = pd.to_datetime(df['release_date'], format='mixed')

In [11]:
df['release_date'].dtype
df['release_date'].head(21)

0    1982-10-27
1    2007-04-16
2    2006-11-06
3    1984-08-21
4    2004-01-01
5    2020-07-31
6    2020-08-07
7    2009-12-28
8    2000-10-24
9    2007-05-15
10   2018-11-09
11   2020-01-17
12   2018-03-21
13   2016-07-29
14   1982-04-08
15   2020-08-03
16   2007-10-30
17   2016-10-28
18   1993-01-01
19   2018-11-16
20   2012-09-07
Name: release_date, dtype: datetime64[ns]

In [12]:
df['release_date'].isna().sum()

np.int64(0)

In [ ]:
#cleaning trail spaces for name, artist, and album
#lowercasing all mood labels to avoid future SQL problems